#!/usr/bin/env python3
"""Package the distributable artifacts.

Two shapes, one source. `SKILL.md` and `catalog/` at the repo root are the only
copies anyone edits; everything below is assembled from them.

  dist/matim.zip   the uploadable skill bundle. claude.ai expects a .zip whose
                   root holds ONE folder with SKILL.md at its top level.
  plugin/          the Claude Code plugin -- skill and connector in one install.
                   Committed to the tree, because `/plugin marketplace add`
                   reads the git checkout; it is generated, so CI checks it has
                   not drifted from the root copies.
"""
import json, os, shutil, zipfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DIST = os.path.join(ROOT, "dist")
PLUGIN = os.path.join(ROOT, "plugin")
MCP_URL = "https://matim-mcp.vercel.app/api/mcp"

VERSION = "0.1.0"
DESCRIPTION = ("Finds the Israeli skill that fits your question in the open skills-il catalog, "
               "loads it for that one task, and forgets it. Hebrew-first: tax, pensions, "
               "ביטוח לאומי, government forms, law, RTL and Israeli formats.")


def catalog_files():
    return sorted(f for f in os.listdir(os.path.join(ROOT, "catalog")) if f.endswith(".md"))


def build_zip():
    os.makedirs(DIST, exist_ok=True)
    out = os.path.join(DIST, "matim.zip")
    files = [("SKILL.md", "SKILL.md")] + [(f"catalog/{f}", f"catalog/{f}") for f in catalog_files()]
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as z:
        for src, arc in files:
            z.write(os.path.join(ROOT, src), f"matim/{arc}")
    print(f"{out}  ({os.path.getsize(out):,} bytes, {len(files)} files)")


def write(path, data):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(data if isinstance(data, str) else json.dumps(data, indent=2, ensure_ascii=False) + "\n")


def build_plugin():
    # Regenerated wholesale: a stale file left behind is the failure mode a
    # generated-and-committed directory actually has.
    if os.path.isdir(PLUGIN):
        shutil.rmtree(PLUGIN)

    write(os.path.join(PLUGIN, ".claude-plugin", "plugin.json"), {
        "name": "matim",
        "description": DESCRIPTION,
        "version": VERSION,
        "author": {"name": "ilanvys", "url": "https://github.com/ilanvys/matim"},
        "homepage": "https://ilanvys.github.io/matim/",
        "license": "MIT",
    })

    # The connector. One address, and it is the only thing here that will ever
    # need changing -- see plans/05 Q7 before it moves.
    write(os.path.join(PLUGIN, ".mcp.json"),
          {"mcpServers": {"matim": {"type": "http", "url": MCP_URL}}})

    skill = os.path.join(PLUGIN, "skills", "matim")
    os.makedirs(skill, exist_ok=True)
    shutil.copy(os.path.join(ROOT, "SKILL.md"), os.path.join(skill, "SKILL.md"))
    os.makedirs(os.path.join(skill, "catalog"), exist_ok=True)
    for f in catalog_files():
        shutil.copy(os.path.join(ROOT, "catalog", f), os.path.join(skill, "catalog", f))

    write(os.path.join(PLUGIN, "README.md"),
          "# matim — Claude Code plugin\n\n"
          "**Generated by `tools/build_bundles.py`. Do not edit by hand.**\n"
          "`SKILL.md` and `catalog/` at the repo root are the source of truth.\n\n"
          "Installs both halves in one command — the skill that decides which Israeli guide a\n"
          "question needs, and the connector that fetches it:\n\n"
          "```\n/plugin marketplace add ilanvys/matim\n/plugin install matim@matim\n```\n\n"
          f"The connector points at `{MCP_URL}`. Nothing is stored; skill content is fetched\n"
          "live from the public skills-il repos. MIT.\n")

    n = 2 + 1 + len(catalog_files()) + 1
    print(f"{PLUGIN}/  ({n} files, skill + connector)")


def build_marketplace():
    # The repo doubles as a single-plugin marketplace, so `/plugin marketplace
    # add ilanvys/matim` is the whole discovery step.
    write(os.path.join(ROOT, ".claude-plugin", "marketplace.json"), {
        "name": "matim",
        "description": "The matim skill and its fetch connector, in one install.",
        "owner": {"name": "ilanvys", "url": "https://github.com/ilanvys/matim"},
        "plugins": [{
            "name": "matim",
            "description": DESCRIPTION,
            "author": {"name": "ilanvys"},
            "source": "./plugin",
            "category": "productivity",
            "homepage": "https://ilanvys.github.io/matim/",
        }],
    })
    print(f"{ROOT}/.claude-plugin/marketplace.json")


if __name__ == "__main__":
    build_zip()
    build_plugin()
    build_marketplace()
